FROM openjdk:17-jdk-alpine
MAINTAINER ZIFAN_WEN


RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

ADD target/auth*.jar /app.jar
ADD run.sh /run.sh
RUN chmod +x /run.sh
# 设置暴露的端口号
EXPOSE 9701
CMD ["/run.sh"]