FROM openjdk:17-jdk-alpine
MAINTAINER ZIFAN_WEN


RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

ADD target/game-server-log-show*.jar /app.jar
ADD run.sh /run.sh
RUN chmod +x /run.sh
# 设置暴露的端口号
EXPOSE 9707
# 在镜像运行为容器后执行的命令
ENTRYPOINT ["java","-jar","app.jar","-Dname=game-server-log-show-service","--spring.profiles.active=prod","-Duser.timezone=Asia/Shanghai","-Xms512m","-Xmx1024m","-XX:MetaspaceSize=128m","-XX:MaxMetaspaceSize=512m"]
CMD ["/run.sh"]